### ISSUE TITLE
Get single poll

### ISSUE THREAD

**Issue by knynkwl** [luwes/craft-polls#5] opened 2017-10-29 22:18 UTC
This doesn't seem to be returning a poll. 

What's the syntax for this?
```
{{ craft.polls.getPollById(1).form({ 
  pollResponse: pollResponse|default(null)
}) }}
```

`Craft\Polls_PollModel and its behaviors do not have a method or closure named "form".`

**Comment by luwes** [comment] 2017-10-30 01:11
It's possible to limit the polls it shows or even the questions it shows by the `questions` param. 
The docs have a small snippet on that. So it would be:

```
{{ craft.polls.form({ 
    pollResponse: pollResponse|default(null),
    questions: craft.polls.questions({ pollId: 1 })
}) }}
```

I believe it's not a bug so closing this.

**Closed as completed by luwes** 2017-10-30 01:11 UTC
Labels: question
